name: Build All (Linux)

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build-dspp:
    runs-on: ubuntu-latest
    name: Builds DSPP library
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'  # or whatever version you want

      - name: Create Build Directory
        run: cmake -E make_directory build
        working-directory: dspp/Linux/dspp

      - name: Run CMake (Xcode Generator)
        run: cmake -S . -B build -G Ninja -DCMAKE_OSX_ARCHITECTURES=x86_64
        working-directory: dspp/Linux/dspp

      - name: Build Project
        run: cmake --build build --config Release
        working-directory: dspp/Linux/dspp

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dspp
          path: dspp/Linux/dspp/build
  build-cmdline:
    runs-on: ubuntu-latest
    name: Builds DSPP Commandline test
    needs: build-dspp
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install libudev (HIDAPI Dependency)
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Download artifact from DSPP
        uses: actions/download-artifact@v4
        with:
          name: dspp
          path: dspp/Linux/dspp/build

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'  # or whatever version you want

      - name: Create Build Directory
        run: cmake -E make_directory build
        working-directory: dspp/Linux/tests/cmdline

      - name: Run CMake (Xcode Generator)
        run: cmake -S . -B build -G Ninja -DCMAKE_OSX_ARCHITECTURES=x86_64
        working-directory: dspp/Linux/tests/cmdline

      - name: Build Project
        run: cmake --build build --config Release
        working-directory: dspp/Linux/tests/cmdline
  build-gui:
    runs-on: ubuntu-latest
    name: Builds DSPP GUI test
    needs: build-dspp
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download artifact from DSPP
        uses: actions/download-artifact@v4
        with:
          name: dspp
          path: dspp/Linux/dspp/build

      - name: Install libudev (HIDAPI Dependency)
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'  # or whatever version you want

      - name: Create Build Directory
        run: cmake -E make_directory build
        working-directory: dspp/Linux/tests/gui

      - name: Run CMake (Xcode Generator)
        run: cmake -S . -B build -G Ninja -DCMAKE_OSX_ARCHITECTURES=x86_64
        working-directory: dspp/Linux/tests/gui

      - name: Build Project
        run: cmake --build build --config Release
        working-directory: dspp/Linux/tests/gui
