name: Build All (Windows)

on:
  push:
    branches: [ "latest" ]
  pull_request:
    branches: [ "latest" ]

env:
  SOLUTION_FILE_PATH: "./dspp/Windows/DualSense C++ For Windows.sln"
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    name: Build DSPP and Tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Entire Solution
        run: |
          msbuild "${{env.SOLUTION_FILE_PATH}}" ^
            /p:Configuration=${{env.BUILD_CONFIGURATION}} ^
            /p:PlatformToolset=v143 ^
            /p:LanguageStandard=stdcpp20 ^
            /p:VCToolsVersion=14.43.34808 ^
            /m

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dspp-build
          path: |
            dspp/Windows/**/x64/Release/*.exe
            dspp/Windows/**/x64/Release/*.dll
            dspp/Windows/**/x64/Release/*.lib
